### ISSUE TITLE
ordre des lettres de la progression

### ISSUE THREAD

**Issue by Anne-et-Claire** [louiiuol/la-methode-claire#13]
## Contexte 📝

> -Les lettres sont à mattre dans cet ordre : A E I O U Y É È Ê

## A faire 💪

-

**Comment by louiiuol** [comment]
<img width="218" alt="image" src="https://github.com/louiiuol/la-methode-claire/assets/14725008/d254c593-3d8b-4a25-8cfd-04ea7b3f920b">
 Je viens de réorganisé les lettres dans l'ordre alphabétique. Mais ce n'est pas le même ordre que décrit ci-dessus. @Anne-et-Claire Est ce obligatoire d'avoir "é" - "è" - "ê" à la fin ?

**Comment by louiiuol** [comment]
Comme vu avec Claire, l'ordre a été modifié
