### ISSUE TITLE
Page: La méthode

### ISSUE THREAD

**Issue by Anne-et-Claire** [louiiuol/la-methode-claire#15]
## Contexte 📝

> -
[pageLaMéthode.pdf](https://github.com/louiiuol/la-methode-claire/files/12728127/pageLaMethode.pdf)

![obstacleAN](https://github.com/louiiuol/la-methode-claire/assets/139384979/2311c828-e56d-40f1-9617-93960530e080)
![obstacleENT](https://github.com/louiiuol/la-methode-claire/assets/139384979/21451f0e-994d-4d7e-bf60-3f1248c9cf53)
![obstacleVCV](https://github.com/louiiuol/la-methode-claire/assets/139384979/10e6321d-ccf3-48b9-8bb6-d708740398a2)
[leçon3-R.pdf](https://github.com/louiiuol/la-methode-claire/files/12728148/lecon3-R.pdf)
[leçon3-R1.pdf](https://github.com/louiiuol/la-methode-claire/files/12728149/lecon3-R1.pdf)

## A faire 💪
[affiche8-ours-OU.pdf](https://github.com/louiiuol/la-methode-claire/files/12728140/affiche8-ours-OU.pdf)
[afficheC.pdf](https://github.com/louiiuol/la-methode-claire/files/12728141/afficheC.pdf)
[exercices13-P-ER-ET-EZ.pdf](https://github.com/louiiuol/la-methode-claire/files/12728142/exercices13-P-ER-ET-EZ.pdf)

-

**Comment by louiiuol** [comment]
Intégrationde la page "La méthode" faite

[La Méthode.pdf](https://github.com/louiiuol/la-methode-claire/files/13455014/La.Methode.pdf)
