### ISSUE TITLE
Page: Qui est claire 

### ISSUE THREAD

**Issue by Anne-et-Claire** [louiiuol/la-methode-claire#16]
## Contexte 📝

> page de présentation de Claire:
- Historique
- Motivations
- invitation à la suivre sur les réseaux sociaux

## A faire 💪

- [x] Préparation du contenu (Claire)
- [x] Illustration d'accompagnement (Nane)
- [x] Création d'un wireframe (Louis & Nane)
- [x] Intégration d'un wireframe (Louis)

## Informations complémentaires 🔎

> Il faudrait rester synthétique, ou du moins organisé le contenu en deux espace:
- l'intro simple mais efficace (en 30sec on voit bien le pourquoi du comment)
- En dessous, des blocs plus détaillé (à voir en fonction du contenu)

[pageQuiestClaire.pdf](https://github.com/louiiuol/la-methode-claire/files/12728172/pageQuiestClaire.pdf)

![quiestclaireblanc](https://github.com/louiiuol/la-methode-claire/assets/139384979/11ceee6b-5c3b-4140-831e-b270b780e4e6)
![sommet](https://github.com/louiiuol/la-methode-claire/assets/139384979/edcdeda8-534e-48ec-acc9-3ec500c4d516)
![FFB66A6C-E7E7-4EB1-9532-418F3A27BFF6_1_105_c](https://github.com/louiiuol/la-methode-claire/assets/139384979/c5f10e7a-3d41-4ec6-b92d-6429ad13cefb)

**Comment by louiiuol** [comment]
Première version du wireframe ajouté sur Figma:
- Beaucoup de contenu (peut être un peu trop; les paragraphes sont très volumineux, ca ne donne pas envie de lire :/ )
- Besoin de voir ensemble quelques détails avant de réellement intégrer la page

**Comment by louiiuol** [comment]
Première intégration faite, en attente des retours pour corriger les coquilles
